/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IntendedUseRouteImport } from './routes/intended-use'
import { Route as LinksRouteImport } from './routes/links'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ConnectorsIndexRouteImport } from './routes/connectors.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1McpRouteImport } from './routes/api/v1/mcp'
import { Route as ConnectorsSetupBrokerRouteImport } from './routes/connectors.setup.$broker'
import { Route as ApiV1HealthAuthRouteImport } from './routes/api/v1/health/auth'
import { Route as ApiV1JobsTokenRefreshRouteImport } from './routes/api/v1/jobs/token-refresh'
import { Route as ApiV1PortfolioSummaryRouteImport } from './routes/api/v1/portfolio/summary'
import { Route as ApiV1OauthBrokerCallbackRouteImport } from './routes/api/v1/oauth/$broker/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IntendedUseRoute = IntendedUseRouteImport.update({
  id: '/intended-use',
  path: '/intended-use',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsIndexRoute = ConnectorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectorsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1McpRoute = ApiV1McpRouteImport.update({
  id: '/api/v1/mcp',
  path: '/api/v1/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsSetupBrokerRoute = ConnectorsSetupBrokerRouteImport.update({
  id: '/setup/$broker',
  path: '/setup/$broker',
  getParentRoute: () => ConnectorsRoute,
} as any)
const ApiV1HealthAuthRoute = ApiV1HealthAuthRouteImport.update({
  id: '/api/v1/health/auth',
  path: '/api/v1/health/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JobsTokenRefreshRoute = ApiV1JobsTokenRefreshRouteImport.update({
  id: '/api/v1/jobs/token-refresh',
  path: '/api/v1/jobs/token-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PortfolioSummaryRoute = ApiV1PortfolioSummaryRouteImport.update({
  id: '/api/v1/portfolio/summary',
  path: '/api/v1/portfolio/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OauthBrokerCallbackRoute =
  ApiV1OauthBrokerCallbackRouteImport.update({
    id: '/api/v1/oauth/$broker/callback',
    path: '/api/v1/oauth/$broker/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/intended-use': typeof IntendedUseRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/mcp': typeof ApiV1McpRoute
  '/connectors/setup/$broker': typeof ConnectorsSetupBrokerRoute
  '/api/v1/health/auth': typeof ApiV1HealthAuthRoute
  '/api/v1/jobs/token-refresh': typeof ApiV1JobsTokenRefreshRoute
  '/api/v1/portfolio/summary': typeof ApiV1PortfolioSummaryRoute
  '/api/v1/oauth/$broker/callback': typeof ApiV1OauthBrokerCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/intended-use': typeof IntendedUseRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/connectors': typeof ConnectorsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/mcp': typeof ApiV1McpRoute
  '/connectors/setup/$broker': typeof ConnectorsSetupBrokerRoute
  '/api/v1/health/auth': typeof ApiV1HealthAuthRoute
  '/api/v1/jobs/token-refresh': typeof ApiV1JobsTokenRefreshRoute
  '/api/v1/portfolio/summary': typeof ApiV1PortfolioSummaryRoute
  '/api/v1/oauth/$broker/callback': typeof ApiV1OauthBrokerCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/intended-use': typeof IntendedUseRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/mcp': typeof ApiV1McpRoute
  '/connectors/setup/$broker': typeof ConnectorsSetupBrokerRoute
  '/api/v1/health/auth': typeof ApiV1HealthAuthRoute
  '/api/v1/jobs/token-refresh': typeof ApiV1JobsTokenRefreshRoute
  '/api/v1/portfolio/summary': typeof ApiV1PortfolioSummaryRoute
  '/api/v1/oauth/$broker/callback': typeof ApiV1OauthBrokerCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connectors'
    | '/dashboard'
    | '/intended-use'
    | '/links'
    | '/login'
    | '/privacy'
    | '/security'
    | '/settings'
    | '/terms'
    | '/connectors/'
    | '/api/auth/$'
    | '/api/v1/mcp'
    | '/connectors/setup/$broker'
    | '/api/v1/health/auth'
    | '/api/v1/jobs/token-refresh'
    | '/api/v1/portfolio/summary'
    | '/api/v1/oauth/$broker/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/intended-use'
    | '/links'
    | '/login'
    | '/privacy'
    | '/security'
    | '/settings'
    | '/terms'
    | '/connectors'
    | '/api/auth/$'
    | '/api/v1/mcp'
    | '/connectors/setup/$broker'
    | '/api/v1/health/auth'
    | '/api/v1/jobs/token-refresh'
    | '/api/v1/portfolio/summary'
    | '/api/v1/oauth/$broker/callback'
  id:
    | '__root__'
    | '/'
    | '/connectors'
    | '/dashboard'
    | '/intended-use'
    | '/links'
    | '/login'
    | '/privacy'
    | '/security'
    | '/settings'
    | '/terms'
    | '/connectors/'
    | '/api/auth/$'
    | '/api/v1/mcp'
    | '/connectors/setup/$broker'
    | '/api/v1/health/auth'
    | '/api/v1/jobs/token-refresh'
    | '/api/v1/portfolio/summary'
    | '/api/v1/oauth/$broker/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectorsRoute: typeof ConnectorsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  IntendedUseRoute: typeof IntendedUseRoute
  LinksRoute: typeof LinksRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1McpRoute: typeof ApiV1McpRoute
  ApiV1HealthAuthRoute: typeof ApiV1HealthAuthRoute
  ApiV1JobsTokenRefreshRoute: typeof ApiV1JobsTokenRefreshRoute
  ApiV1PortfolioSummaryRoute: typeof ApiV1PortfolioSummaryRoute
  ApiV1OauthBrokerCallbackRoute: typeof ApiV1OauthBrokerCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intended-use': {
      id: '/intended-use'
      path: '/intended-use'
      fullPath: '/intended-use'
      preLoaderRoute: typeof IntendedUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/': {
      id: '/connectors/'
      path: '/'
      fullPath: '/connectors/'
      preLoaderRoute: typeof ConnectorsIndexRouteImport
      parentRoute: typeof ConnectorsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/mcp': {
      id: '/api/v1/mcp'
      path: '/api/v1/mcp'
      fullPath: '/api/v1/mcp'
      preLoaderRoute: typeof ApiV1McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/setup/$broker': {
      id: '/connectors/setup/$broker'
      path: '/setup/$broker'
      fullPath: '/connectors/setup/$broker'
      preLoaderRoute: typeof ConnectorsSetupBrokerRouteImport
      parentRoute: typeof ConnectorsRoute
    }
    '/api/v1/health/auth': {
      id: '/api/v1/health/auth'
      path: '/api/v1/health/auth'
      fullPath: '/api/v1/health/auth'
      preLoaderRoute: typeof ApiV1HealthAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jobs/token-refresh': {
      id: '/api/v1/jobs/token-refresh'
      path: '/api/v1/jobs/token-refresh'
      fullPath: '/api/v1/jobs/token-refresh'
      preLoaderRoute: typeof ApiV1JobsTokenRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/portfolio/summary': {
      id: '/api/v1/portfolio/summary'
      path: '/api/v1/portfolio/summary'
      fullPath: '/api/v1/portfolio/summary'
      preLoaderRoute: typeof ApiV1PortfolioSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/oauth/$broker/callback': {
      id: '/api/v1/oauth/$broker/callback'
      path: '/api/v1/oauth/$broker/callback'
      fullPath: '/api/v1/oauth/$broker/callback'
      preLoaderRoute: typeof ApiV1OauthBrokerCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConnectorsRouteChildren {
  ConnectorsIndexRoute: typeof ConnectorsIndexRoute
  ConnectorsSetupBrokerRoute: typeof ConnectorsSetupBrokerRoute
}

const ConnectorsRouteChildren: ConnectorsRouteChildren = {
  ConnectorsIndexRoute: ConnectorsIndexRoute,
  ConnectorsSetupBrokerRoute: ConnectorsSetupBrokerRoute,
}

const ConnectorsRouteWithChildren = ConnectorsRoute._addFileChildren(
  ConnectorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectorsRoute: ConnectorsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  IntendedUseRoute: IntendedUseRoute,
  LinksRoute: LinksRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1McpRoute: ApiV1McpRoute,
  ApiV1HealthAuthRoute: ApiV1HealthAuthRoute,
  ApiV1JobsTokenRefreshRoute: ApiV1JobsTokenRefreshRoute,
  ApiV1PortfolioSummaryRoute: ApiV1PortfolioSummaryRoute,
  ApiV1OauthBrokerCallbackRoute: ApiV1OauthBrokerCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
